- hosts: webserver
  gather_facts: yes
  
  tasks:
    - name: Copy shell script to target host
      copy:
        src: /home/ubuntu/fyp/deploy-script.sh
        dest: /home/ubuntu/fyp/deploy-script.sh
        

    - name: Execute shell script on target host
      shell: /home/ubuntu/fyp/deploy-script.sh
