- hosts: all
  gather_facts: yes
  remote_user: ubuntu
  become: true
  
  tasks:
    - name: Copy shell script to target host
      copy:
        src: /var/lib/jenkins/workspace/fyp/fyp/deploy-script.sh
        dest: /home/ubuntu/fyp/deploy-script.sh

    - name: Make script executable
      shell: chmod +x /home/ubuntu/fyp/deploy-script.sh
        
    - name: test
      shell: mkdir veeren2

    - name: Execute shell script on target host
      shell: cd /home/ubuntu/fyp && ./deploy-script.sh
